// Add your code here
valon3.motorRun(valon3.Motors.MAll, valon3.Dir.CW, 100)
basic.pause(1000)
valon3.motorRun(valon3.Motors.MAll, valon3.Dir.CCW, 100)
basic.pause(1000)
valon3.motorStop(valon3.Motors.MAll)

valon3.Ultrasonic(0)

let eyes = valon3.create(2, valon3.EyesMode.RGB)
eyes.setEyesColor(valon3.RGBEYES.EyesLeft, valon3.colors(valon3.EyesColors.Red))
eyes.setBrightness(255)
basic.pause(1000)
eyes.clear()
valon3.colors(valon3.EyesColors.Green)
eyes.showColor(valon3.colors(valon3.EyesColors.Green))
basic.pause(500)
valon3.rgb(255, 255, 255)
valon3.hsl(100, 50, 50)
eyes.setPixelColor(1, valon3.colors(valon3.EyesColors.Blue))
eyes.setPixelColor(0, valon3.colors(valon3.EyesColors.Blue))
eyes.show()
basic.pause(500)
valon3.connectIrReceiver(DigitalPin.P3, valon3.IrProtocol.NEC)